// Generated by generate.mjs: this package's API on each marketplace.
export const API_TITLE = 'Website Technology Stack Detector';
export const API_MARKET_SLUG = 'tech-stack-detector';
export const RAPIDAPI_HOST = 'website-technology-stack-detector.p.rapidapi.com';
